In [1]:
import pandas as pd
import mysql.connector
import time

In [2]:
# Reemplaza los valores con tus credenciales de MySQL
conn = mysql.connector.connect(
    host='localhost',
    user='root',
    password='2808',
    database='dev_fertigar_yii',
    port=3307
)

In [53]:
path_productos = r"C:\xampp\htdocs\dev.fertigar_yii\catalogos\productos.xlsx"
path_proveedores = r"C:\xampp\htdocs\dev.fertigar_yii\catalogos\proveedores.xlsx"
path_clientes = r"C:\xampp\htdocs\dev.fertigar_yii\catalogos\clientes.xlsx"
path_agentes = r"C:\xampp\htdocs\dev.fertigar_yii\catalogos\agentes.xlsx"

In [25]:
df_p = pd.read_excel(path_productos)
del df_p["Unnamed: 13"]
del df_p["Precio 1 (Especial)"]

In [26]:
df_p['Unidad XML'] = df_p['Unidad XML'].fillna("H87")
df_p.rename(columns={
    'CLASIFICACIÓN PRODUCTO 1': 'cat',
    'Precio 1 (Especial)': 'p_especial',
    'Precio 2 (Subdistribuidor)': 'p_sub',
    'Precio 3 (Mayoreo)': 'p_mayoreo',
    'Precio 4 (Público)': 'p_publico',
    'NOMBRE PRODUCTO': 'nombre',
    'CODIGO PRODUCTO': 'codigo',
    'PROVEEDOR': 'proveedor',
    'Unidad XML': 'unidad_sat',
    'CLAVE SAT': 'clave_sat',
}, inplace=True)

In [36]:
df_p.head(5)

,No.,codigo,nombre,p_sub,p_mayoreo,p_publico,cat,clave_sat,proveedor,IVA,IEPS,unidad_sat,unidad_sat_id,cat_id
0,1,ABBSALC20L,ALCAPLANT 20 KG,0.00,0.00,0.00,FERTILIZANTES SOLUBLES,10171505.0,ABBSA,0,0,H87,3,2727.0
1,2,ADABUM1,BUMPER 25 CE LT,0.00,0.00,0.00,FUNGICIDAS,10171702.0,ADAMA,0,0,LTR,2,2680.0
2,3,ADAMAFOLPA,FOLPAN 80 WDG KG,249.06,261.74,275.47,FUNGICIDAS,51101800.0,ADAMA,0,6,KGM,1,2680.0
3,4,ADAOXI851,OXICOB 85 KG,201.31,210.00,219.61,FUNGICIDAS,10171702.0,ADAMA,0,0,KGM,1,2680.0
4,5,AFOSFKGA20,ACIDO FOSFORICO 75% 20LT,950.00,1000.00,1050.00,FERTILIZANTES SOLUBLES,10171504.0,KER AGRO,0,0,H87,3,2727.0

In [46]:
df_p['cat'].value_counts()
#
#kgm -> 1 
#ltr     -> 2
# H87 -> 3

cat
INSECTICIDAS                     156
FUNGICIDAS                        98
NUTRIENTES FOLIARES               94
HERBICIDAS                        58
BIOESTIMULANTES                   37
(Ninguna)                         34
FERTILIZANTES SOLUBLES            29
COADYUVANTES                      28
NUTRIENTES PARA FERTIRIGACIÓN     24
FERTILIZANTES GRANULADOS          23
MEJORADORES DE SUELO              21
ACARICIDAS                        17
BACTERICIDAS                      10
BIOPROTECTORES                     8
REGULADOR DE CRECIMIENTO           7
ENRAIZADOR                         3
RODENTICIDA                        1
Name: count, dtype: int64

In [28]:
df_p['unidad_sat_id'] = df_p['unidad_sat'].map({
    'KGM': 1,
    'LTR': 2,
    'H87': 3,
})

In [47]:
cat_map = {
    'INSECTICIDAS': '2679',
    'FUNGICIDAS': '2680',
    'NUTRIENTES FOLIARES': '2699',
    'HERBICIDAS': '2725',
    'BIOESTIMULANTES': '2726',
    'FERTILIZANTES SOLUBLES': '2727',
    'COADYUVANTES': '2728',
    'NUTRIENTES PARA FERTIRIGACIÓN': '2729',
    'FERTILIZANTES GRANULADOS': '2730',
    'MEJORADORES DE SUELO': '2731',
    'ACARICIDAS': '2732',
    'BACTERICIDAS': '2733',
    'BIOPROTECTORES': '2734',
    'REGULADOR DE CRECIMIENTO': '2735',
    'ENRAIZADOR': '2736',
    'RODENTICIDA': '2737',
    '(Ninguna)' : '2738'
}
cat_map

{'INSECTICIDAS': '2679',
 'FUNGICIDAS': '2680',
 'NUTRIENTES FOLIARES': '2699',
 'HERBICIDAS': '2725',
 'BIOESTIMULANTES': '2726',
 'FERTILIZANTES SOLUBLES': '2727',
 'COADYUVANTES': '2728',
 'NUTRIENTES PARA FERTIRIGACIÓN': '2729',
 'FERTILIZANTES GRANULADOS': '2730',
 'MEJORADORES DE SUELO': '2731',
 'ACARICIDAS': '2732',
 'BACTERICIDAS': '2733',
 'BIOPROTECTORES': '2734',
 'REGULADOR DE CRECIMIENTO': '2735',
 'ENRAIZADOR': '2736',
 'RODENTICIDA': '2737',
 '(Ninguna)': '2738'}

In [48]:
df_p['cat_id'] = df_p['cat'].map(cat_map)

In [49]:
df_p['clave_sat'] = df_p['clave_sat'].fillna(0).astype(int).astype(str)
df_p['cat_id'] = df_p['cat_id'].fillna(0).astype(int).astype(str)
df_p['created_by'] = 1
df_p['created_at'] = int(time.time())

In [41]:
df_p.head(2)

,No.,codigo,nombre,p_sub,p_mayoreo,p_publico,cat,clave_sat,proveedor,IVA,IEPS,unidad_sat,unidad_sat_id,cat_id,created_by,created_at
0,1,ABBSALC20L,ALCAPLANT 20 KG,0.0,0.0,0.0,FERTILIZANTES SOLUBLES,10171505,ABBSA,0,0,H87,3,2727,1,1752167264
1,2,ADABUM1,BUMPER 25 CE LT,0.0,0.0,0.0,FUNGICIDAS,10171702,ADAMA,0,0,LTR,2,2680,1,1752167264

In [52]:
#inser 
cursor = conn.cursor()
insert_query = """
INSERT INTO producto (clave, clave_sat, nombre, ieps, iva, unidad_medida_id, categoria_id,
 precio_publico, precio_sub, precio_mayoreo, created_by, created_at)
 values (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
"""
data_to_insert = df_p[['codigo', 'clave_sat', 'nombre', 'IEPS', 'IVA', 'unidad_sat_id', 'cat_id',
                       'p_publico', 'p_sub', 'p_mayoreo', 'created_by', 'created_at']].values.tolist()

cursor.executemany(insert_query, data_to_insert)
conn.commit()
cursor.close()

True

## PROVEEDOR

In [77]:
df_pv = pd.read_excel(path_proveedores)

In [69]:
df_pv.head(3)
#df_pv['País'].unique()

,code,nombre,rfc,Calle,Ciudad,Código Postal,Colonia,correo,Estado,Municipio,Número Exterior,Número Interior,País
0,AAG070412F46,AFM AGROS SA DE CV,AAG070412F46,Bodega,Uruapan,60190.0,Quirindavara,NaN,Michoacán,Uruapan,17,A,México
1,AAG1604282M1,AVOBERRIES AGROQUIMICOS,AAG1604282M1,HILANDEROS,Uruapan,60080.0,LA MAGDALENA,auxgerencia1@avoberries.com,Michoacán,Uruapan,78,NaN,México
2,AAZG890630CJ3,GABRIELA ANDRADE ZAMORA,AAZG890630CJ3,Blv Luis Donaldo Colosio,Tancitaro,60460.0,Centro,agrohass.agroquimica@hotmail.com,Michoacán,Tancítaro,75,NaN,México

In [78]:
columns_ocupar = ['code', 'nombre', 'rfc']
df_pv = df_pv[columns_ocupar]
df_pv['created_by'] = 1
df_pv['created_at'] = int(time.time())
df_pv['rfc'] = df_pv['rfc'].fillna("") .astype(str)
df_pv['nombre'] = df_pv['nombre'].apply(lambda x: x.strip().upper() if isinstance(x, str) else x)
df_pv['nombre'] = df_pv['nombre'].fillna("") .astype(str)
df_pv['nombre_'] = df_pv['nombre'].fillna("") .astype(str)

df_pv['code'] = df_pv['code'].fillna("") .astype(str)


df_pv

,code,nombre,rfc,created_by,created_at,nombre_
0,AAG070412F46,AFM AGROS SA DE CV,AAG070412F46,1,1752169014,AFM AGROS SA DE CV
1,AAG1604282M1,AVOBERRIES AGROQUIMICOS,AAG1604282M1,1,1752169014,AVOBERRIES AGROQUIMICOS
2,AAZG890630CJ3,GABRIELA ANDRADE ZAMORA,AAZG890630CJ3,1,1752169014,GABRIELA ANDRADE ZAMORA
3,AFE130307PW,AGRO-PER FERTILIZANTES,AFE130307PW4,1,1752169014,AGRO-PER FERTILIZANTES
4,AFLAGRO,AFL AGRO,,1,1752169014,AFL AGRO
...,...,...,...,...,...,...
91,VEMJ8204087W7,JUAN CARLOS VEGA MENDEZ,VEMJ8204087W7,1,1752169014,JUAN CARLOS VEGA MENDEZ
92,VIDRANA811125V12,VIDRA,ANA811125V12,1,1752169014,VIDRA
93,VME940419T62,VALENT DE MEXICO,VME940419T62,1,1752169014,VALENT DE MEXICO
94,XAXX010101000,PUBLICO EN GENERAL,XAXX010101000,1,1752169014,PUBLICO EN GENERAL
95,YCO140516MV5,YESERA COMERCIAL SA,YCO140516MV5,1,1752169014,YESERA COMERCIAL SA

In [79]:
#inser 
cursor = conn.cursor()
insert_query = """
INSERT INTO proveedor (nombre, razon_social, rfc, created_by, created_at)
 values (%s, %s, %s, %s, %s)
"""
data_to_insert = df_pv[['nombre', 'nombre_', 'rfc', 
                        'created_by', 'created_at']].values.tolist()

cursor.executemany(insert_query, data_to_insert)
conn.commit()
cursor.close()

True

## CLIENTES

In [102]:
df_c = pd.read_excel(path_clientes)
df_c

,CÓDIGO CLIENTE,RAZÓN SOCIAL,R.F.C.,LÍMITE DE CRÉDITO,CALLE,CIUDAD,CODIGO POSTAL,COLONIA,eMail,ESTADO,MUNICIPIO,NUM. EXTERIOR,NUM INTERIOR,PAÍS,REGIMEN FISCAL,USO CFDI,LISTA DE PRECIOS
0,1SA221103DU0,INSUMOS Y SERVICIOS AGROVAL,ISA221103DU0,0,LA PINTA,NaN,61830.0,JARDINES DE SANTA MARIA,sucursal.arioagroval@gmail.com,Michoacán,Ario,91,NaN,México,601.0,G01,2
1,AAA170609DYA,ALMA,AAA170609DYA,0,LAS NORIAS DE BAJAN,NaN,58350.0,Hacienda del Monte,NaN,Michoacán,Morelia,128,NaN,México,603.0,G03,1
2,AAA200306LNA,AGUACATE Y ARANDANO LA ARIENSE,AAA200306LNA,0,abasolo,NaN,61830.0,NaN,NaN,Michoacán,Ario,84,NaN,México,622.0,G03,2
3,AAAA710605IF0,ALFREDO ALFARO ARCE,AAAA710605IF0,0,INDEPENDENCIA,Yurécuaro,59250.0,YURECUARO CENTRO,NaN,Michoacán,Yurécuaro,NaN,NaN,México,NaN,G03,1
4,AAAB020714850,JOSE BRANDON AYALA ALFARO,AAAB020714850,1,3A PRIVADA VICENTE GUERRERO,NaN,60221.0,OTRA NO ESPECIFICADA,NaN,Michoacán,NaN,19,NaN,México,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1517,ZEME640813S17,MA. ELENA ZEPEDA MARTINEZ,ZEME640813S17,0,REVOLUCIO,TARETAN,61710.0,BARRIO ALTO,NaN,MICHOACAN DE OCAMPO,TARETAN,878,NaN,México,626.0,G03,3
1518,ZET240325KI1,ZARZAMORAS ERANDI DE TARETAN,ZET240325KI1,0,16 DE SEPTIEMBRE,NaN,61710.0,CENTRO,NaN,Michoacán,Taretan,122,NaN,México,622.0,G03,1
1519,ZUBV9205041M3K,VICTOR GABRIEL ZUÑIGA BONILLA,ZUBV9205041M3,0,MAANUEL NUÑES MENDOZA,Tacámbaro de Codallos,61650.0,Jardines de La Purísima,NaN,Michoacán,Tacámbaro,176,NaN,México,612.0,G01,2
1520,ZUMG9804113V3,GLORIA ZUÑIGA MORENO,ZUMG9804113V3,0,JESUS MONTE,Morelia,58090.0,LOMAS DE SANTA MARIA,NaN,Michoacán,Morelia,1963 B,NaN,México,612.0,G03,2
1521,ZUVS840720KG8,SERGIO FERNANDO ZURITA VALENCIA,ZUVS840720KG8,0,Camino al Manzanillal,NaN,61615.0,NaN,administracion@lvavocados.com,Michoacán,Pátzcuaro,3300,3,México,612.0,G03,1

In [89]:
columnas_ocupar = ['CÓDIGO CLIENTE', 'RAZÓN SOCIAL', 'R.F.C.','eMail','REGIMEN FISCAL','PAÍS','USO CFDI','LISTA DE PRECIOS']
df_c = df_c[columnas_ocupar]
df_c['created_by'] = 1  
df_c['created_at'] = int(time.time())

In [86]:
df_c.isnull().sum()

CÓDIGO CLIENTE         0
RAZÓN SOCIAL           0
R.F.C.                 2
eMail               1043
REGIMEN FISCAL       637
PAÍS                   0
USO CFDI             344
LISTA DE PRECIOS       0
created_by             0
created_at             0
dtype: int64

In [93]:
df_c['R.F.C.'] = df_c['R.F.C.'].fillna("") .astype(str)
df_c['eMail'] = df_c['eMail'].fillna("") .astype(str)
df_c['REGIMEN FISCAL'] = df_c['REGIMEN FISCAL'].fillna(0).astype(int).astype(str)
df_c['USO CFDI'] = df_c['USO CFDI'].fillna('').astype(str)

In [94]:
df_c.head(3)

,CÓDIGO CLIENTE,RAZÓN SOCIAL,R.F.C.,eMail,REGIMEN FISCAL,PAÍS,USO CFDI,LISTA DE PRECIOS,created_by,created_at
0,1SA221103DU0,INSUMOS Y SERVICIOS AGROVAL,ISA221103DU0,sucursal.arioagroval@gmail.com,601,México,G01,2,1,1752169747
1,AAA170609DYA,ALMA,AAA170609DYA,,603,México,G03,1,1,1752169747
2,AAA200306LNA,AGUACATE Y ARANDANO LA ARIENSE,AAA200306LNA,,622,México,G03,2,1,1752169747

In [97]:
df_c['LISTA DE PRECIOS'].value_counts()

LISTA DE PRECIOS
1    685
4    476
2    285
3     53
7      9
9      8
8      3
6      2
5      1
Name: count, dtype: int64

In [101]:
cursor = conn.cursor()
insert_query = """
INSERT INTO cliente (nombre, uso_cfdi, rfc,email, created_by, created_at)
 values (%s, %s, %s, %s, %s, %s)
"""
data_to_insert = df_c[['RAZÓN SOCIAL', 'USO CFDI', 'R.F.C.', 'eMail',
                        'created_by', 'created_at']].values.tolist()

cursor.executemany(insert_query, data_to_insert)
conn.commit()
cursor.close()

True

In [105]:
# Inserción masiva en la tabla esys_direccion
cursor = conn.cursor()
insert_query = """
INSERT INTO esys_direccion (cuenta, cuenta_id, tipo)
VALUES (%s, %s, %s)
"""
data_to_insert = [(2, i, 1) for i in range(1, 1523)]
cursor.executemany(insert_query, data_to_insert)
conn.commit()
cursor.close()

True

In [ ]:
`esys_direccion`